export enum CollisionType {
	Null = 'eNull',
	Point = 'ePoint',
	LineSeg = 'eLineSeg',
	LineSegSlingshot = 'eLineSegSlingshot',
	Joint = 'eJoint',
	Circle = 'eCircle',
	Flipper = 'eFlipper',
	Plunger = 'ePlunger',
	Spinner = 'eSpinner',
	Ball = 'eBall',
	Poly = 'e3DPoly',
	Triangle = 'eTriangle',
	Plane = 'ePlane',
	Line = 'e3DLine',
	Gate = 'eGate',
	Textbox = 'eTextbox',
	DispReel = 'eDispReel',
	LightSeq = 'eLightSeq',
	Primitive = 'ePrimitive',
	HitTarget = 'eHitTarget',
	Trigger = 'eTrigger',
	Kicker = 'eKicker',
}
